/** The evolution plane: one method draft ledger, one evaluation pipeline, one publish pointer switch, and the read-only projection of a legacy ledger.
 * @module dsh-singularity-evolution */

export * from './types.ts'
export * from './shared.ts'
export * from './model.ts'
export * from './ledger/records.ts'
export * from './ledger/fold.ts'
export * from './draft/draft.ts'
export * from './evidence/receipt.ts'
export * from './evidence/consumption.ts'
export * from './evidence/snapshot.ts'
export * from './evidence/judge.ts'
export * from './history/legacy-reader.ts'
export * from './pipeline/sources.ts'
export * from './pipeline/plan.ts'
export * from './pipeline/run.ts'
export * from './pipeline/validate.ts'
export * from './pipeline/guards.ts'
export * from './pipeline/score.ts'
export * from './pipeline/report.ts'
export * from './pipeline/evaluate.ts'
export * from './draft/adapters.ts'
export * from './service/jsonl-ledger.ts'
export * from './service/runtime-sources.ts'
export * from './publish/request.ts'
export * from './publish/pointer.ts'
export * from './strategy/index.ts'
export * from './capability-candidate.ts'
export * from './legacy/service.ts'

export { default } from './legacy/service.ts'
